// green-wood-parking-ui/src/app/camera-view/camera-view.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, OnDestroy, OnInit, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { DomSanitizer, SafeUrl } from '@angular/platform-browser';
import { Observable } from 'rxjs';

export interface CameraViewData {
  /** Запрашивает кадр (используется при открытии диалога и кнопкой обновления). */
  fetchImage: () => Observable<Blob>;
}

@Component({
  selector: 'app-camera-view',
  templateUrl: './camera-view.component.html',
  styleUrls: ['./camera-view.component.scss'],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, MatDialogModule, MatButtonModule, MatIconModule, MatProgressSpinnerModule]
})
export class CameraViewComponent implements OnInit, OnDestroy {

  private readonly dialogRef = inject(MatDialogRef<CameraViewComponent>);
  private readonly data: CameraViewData = inject(MAT_DIALOG_DATA);
  private readonly sanitizer = inject(DomSanitizer);

  public imagePath = signal<SafeUrl | undefined>(undefined);
  public isLoading = signal(true);
  public isRefreshing = signal(false);
  public error = signal<string | null>(null);

  private objectUrl: string | undefined;

  public ngOnInit(): void {
    this.data.fetchImage().subscribe({
      next: (blob) => {
        this.setImage(blob);
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error(err);
        this.error.set('Не удалось загрузить изображение');
        this.isLoading.set(false);
      }
    });
  }

  public ngOnDestroy(): void {
    this.revokeCurrentUrl();
  }

  public onClose(): void {
    this.dialogRef.close();
  }

  public onRefresh(): void {
    if (this.isRefreshing() || this.isLoading()) {
      return;
    }

    this.isRefreshing.set(true);
    this.error.set(null);

    this.data.fetchImage().subscribe({
      next: (blob) => {
        this.setImage(blob);
        this.isRefreshing.set(false);
      },
      error: (err) => {
        console.error(err);
        this.error.set('Не удалось обновить изображение');
        this.isRefreshing.set(false);
      }
    });
  }

  private setImage(file: Blob): void {
    const previousUrl = this.objectUrl;

    this.objectUrl = URL.createObjectURL(file);
    this.imagePath.set(this.sanitizer.bypassSecurityTrustUrl(this.objectUrl));

    if (previousUrl) {
      URL.revokeObjectURL(previousUrl);
    }
  }

  private revokeCurrentUrl(): void {
    if (this.objectUrl) {
      URL.revokeObjectURL(this.objectUrl);
      this.objectUrl = undefined;
    }
  }

}

<div class="image-viewer">
  @if (imagePath()) {
    <img class="parking-frame" [src]="imagePath()" alt="Parking Stream" (click)="onClose()" />
  }

  @if (isLoading()) {
    <div class="loading-overlay">
      <mat-spinner diameter="48"></mat-spinner>
    </div>
  }

  <button
    mat-fab
    color="primary"
    type="button"
    class="refresh-button"
    [disabled]="isRefreshing() || isLoading()"
    (click)="onRefresh(); $event.stopPropagation()"
    aria-label="Обновить изображение"
  >
    @if (isRefreshing()) {
      <mat-spinner diameter="24" color="accent"></mat-spinner>
    } @else {
      <mat-icon>refresh</mat-icon>
    }
  </button>

  @if (error()) {
    <div class="error-banner">{{ error() }}</div>
  }
</div>

// green-wood-parking-ui-react/src/camera-view/CameraView.tsx
import { useEffect, useRef, useState } from 'react';
import { Button } from '../components/Button/Button';
import { Icon } from '../components/Icon/Icon';
import { Modal } from '../components/Modal/Modal';
import { Spinner } from '../components/Spinner/Spinner';
import styles from './CameraView.module.css';

export interface CameraViewProps {
  /** Запрашивает кадр (используется при открытии диалога и кнопкой обновления). */
  fetchImage: () => Promise<Blob>;
  onClose: () => void;
}

export function CameraView({ fetchImage, onClose }: CameraViewProps) {
  const [imageUrl, setImageUrl] = useState<string | undefined>(undefined);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const objectUrlRef = useRef<string | undefined>(undefined);

  useEffect(() => {
    let cancelled = false;

    fetchImage()
      .then((blob) => {
        if (cancelled) {
          return;
        }
        setImage(blob);
        setIsLoading(false);
      })
      .catch((err: unknown) => {
        if (cancelled) {
          return;
        }
        console.error(err);
        setError('Не удалось загрузить изображение');
        setIsLoading(false);
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- fetch only the initial frame once on mount
  }, []);

  useEffect(() => {
    return () => {
      if (objectUrlRef.current) {
        URL.revokeObjectURL(objectUrlRef.current);
      }
    };
  }, []);

  function setImage(blob: Blob): void {
    const previousUrl = objectUrlRef.current;
    const nextUrl = URL.createObjectURL(blob);
    objectUrlRef.current = nextUrl;
    setImageUrl(nextUrl);

    if (previousUrl) {
      URL.revokeObjectURL(previousUrl);
    }
  }

  function handleRefresh(): void {
    if (isRefreshing || isLoading) {
      return;
    }

    setIsRefreshing(true);
    setError(null);

    fetchImage()
      .then((blob) => {
        setImage(blob);
        setIsRefreshing(false);
      })
      .catch((err: unknown) => {
        console.error(err);
        setError('Не удалось обновить изображение');
        setIsRefreshing(false);
      });
  }

  return (
    <Modal onClose={onClose} panelClassName={styles.panel}>
      <div className={styles.viewer}>
        {imageUrl && (
          <img
            className={styles.frame}
            src={imageUrl}
            alt="Parking Stream"
            role="button"
            tabIndex={0}
            onClick={onClose}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                onClose();
              }
            }}
          />
        )}

        {isLoading && (
          <div className={styles.loadingOverlay}>
            <Spinner diameter={48} />
          </div>
        )}

        <Button
          variant="icon"
          className={styles.refreshButton}
          disabled={isRefreshing || isLoading}
          onClick={(event) => {
            event.stopPropagation();
            handleRefresh();
          }}
          aria-label="Обновить изображение"
        >
          {isRefreshing ? <Spinner diameter={24} /> : <Icon name="refresh" />}
        </Button>

        {error && <div className={styles.errorBanner}>{error}</div>}
      </div>
    </Modal>
  );
}
